replicaCount: 1

namespace: [passed]

serviceCode: [passed]
# localDev will be set in startup script
localDev: 0

image:
  registry: [passed]
  repository: [passed]
  # Pull policy: Always, IfNotPresent, Never
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "145"

strategy:
  type: RollingUpdate
  rollingUpdateMaxSurge: 25%
  rollingUpdateMaxUnavailable: 25%

deployment:
  name: [passed]

service:
  name: [passed]
  # ClusterIP or Node Port
  type: ClusterIP
  portProtocol: TCP
  # Port the service will be listing on
  port: 80
  # Port that pod(s) will be listening on
  targetPort: 80
  portName: default

ingress:
  name: [passed]
  # Traffic arriving at the load balancer to this Domain Name will get routed according to this ingress spec.
  host: [passed]
  # Port on the service to route traffic to.
  port: 80
  tlsSecret: [passed]

resources:
  limits:
    cpu: 1000m
    memory: 2056Mi
  requests:
    cpu: 500m
    memory: 256Mi

selectorLabels:
  # Traffic to this service will be routed to pod(s) with this label.
  app: [passed]

# imagePullSecrets: [name: xyz]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# ingress:
#   enabled: true
#   className: ""
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: laravel-chart.local
#       paths:
#         - path: /
#           pathType: Prefix
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
