apiVersion : apps/v1
kind: Deployment
metadata:
  name: arvigtestcluster334d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arvigtestcluster334d
  template:
    metadata:
      labels:
        app: arvigtestcluster334d
    spec:
      containers:
        - name: arvigtestcluster334d
          image: arvigtestregistry.azurecr.io/arvigtestcluster334d
          ports:
          - containerPort: 80