apiVersion : apps/v1
kind: Deployment
metadata:
  name: arvigtestcluster334d-green
  labels:
    app: arvigtestcluster334d
    slot: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arvigtestcluster334d
      slot: green
  template:
    metadata:
      labels:
        app: arvigtestcluster334d
        slot: green
    spec:
      containers:
        - name: arvigtestcluster334d
          image: arvigtestregistry.azurecr.io/arvigtestcluster334d
          ports:
          - containerPort: 80